02 - Projeto_Crypto_Wallet/crypto_project/config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
  #get 'index', to: 'welcome#index'
  #get 'coins', to: "coins#index"
  # get 'welcome/index'

end

02 - Projeto_Crypto_Wallet/crypto_project/app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
end

02 - Projeto_Crypto_Wallet/crypto_project/app/models/mining_type.rb
class MiningType < ApplicationRecord
   has_many :coins
end

02 - Projeto_Crypto_Wallet/crypto_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
       cookies[:locale] = params[:locale]
    end
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
         I18n.locale = cookies[:locale]
      end
    end
  end
end

02 - Projeto_Crypto_Wallet/crypto_project/app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  layout "adm"
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [:new, :edit, :update, :create ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

02 - Projeto_Crypto_Wallet/crypto_project/app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

02 - Projeto_Crypto_Wallet/crypto_project/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #@nome="Tielle"
    @nome= params[:nome]
    cookies[:curso] ="Curso de Ruby on Rails - COOKIE"
    session[:curso] ="Curso de Ruby on Rails - SESSION"
  end
end

02 - Projeto_Crypto_Wallet/crypto_project/app/helpers/application_helper.rb
module ApplicationHelper

  def data_br(data_us)
    data_us.strftime("%d/%m/%Y")
  end

  def application_name
    "CRYPTO_PROJECT"
  end

  def locale
    I18n.locale == :en ? "Estados Unidos" : "Português do Brasil"
  end

end

02 - Projeto_Crypto_Wallet/crypto_project/app/helpers/coins_helper.rb
module CoinsHelper
end

02 - Projeto_Crypto_Wallet/crypto_project/app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

02 - Projeto_Crypto_Wallet/crypto_project/app/helpers/welcome_helper.rb
module WelcomeHelper

  def ambiente_rails
      if Rails.env.development?
        "Desenvolvimento"
      elsif Rails.env.production?
        "Produção"
      end
    end
end

02 - Projeto_Crypto_Wallet/crypto_project/app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CryptoProject</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<h1>TESTE RUBY - ADM CABEÇALHO</h1>
<%= yield %>
<h1>TESTE RUBY - ADM RODAPÉ</h1>
</body>
</html>

02 - Projeto_Crypto_Wallet/crypto_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>

    <!--Usado por todos. Não é carregado por uma controller específica. -->
    <%= stylesheet_link_tag 'scaffolds', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>



  </head>

  <body>
  <h1>TESTE RUBY - CABEÇALHO <%= params[:controller] %></h1>
    <%= yield %>
    <h1>TESTE RUBY - RODAPÉ</h1>

  <script>
      $.notify("Página carregada!", "success");
  </script>
  </body>
</html>

02 - Projeto_Crypto_Wallet/crypto_project/app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

02 - Projeto_Crypto_Wallet/crypto_project/app/views/mining_types/edit.html.erb
<h1>Editing Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Show', @mining_type %> |
<%= link_to 'Back', mining_types_path %>

02 - Projeto_Crypto_Wallet/crypto_project/app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mining Types</h1>

<table>
  <thead>
    <tr>
      <th><%= MiningType.human_attribute_name("description")%></th>
      <th><%= MiningType.human_attribute_name("acronym")%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mining Type', new_mining_type_path %>

02 - Projeto_Crypto_Wallet/crypto_project/app/views/mining_types/new.html.erb
<h1>New Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Back', mining_types_path %>

02 - Projeto_Crypto_Wallet/crypto_project/app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to 'Edit', edit_mining_type_path(@mining_type) %> |
<%= link_to 'Back', mining_types_path %>