04 - Projeto_Time_to_Answer/time_to_answer/config/routes.rb
Rails.application.routes.draw do

  namespace :admins_backoffice do
    get 'admins/index' #dasboard
    #get 'admins/edit/:id', to: "admins#edit"
    resource :admins #Adminsitradores
    resource :subjects # Assuntos
    resource :questions
    get 'questions/index' #index questions
  end
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    post 'answer', to: 'answer#question'
    get 'subject/:subject_id/:subject_name', to: 'search#subject', as: 'search_subject'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to:'profile#edit'
    #atualização do registro (patch - parte dos dados ou put - todos os dados)
    patch 'profile', to:'profile#update'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  # Bloqueia a rota /admins/sign_up
  #devise_for :admins, :skip => [:registrations] do
  devise_for :admins do
     get 'admins/sign_out', to: 'devise/sessions#destroy'
  end

  devise_for :users

  get 'backoffice', to: 'admins_backoffice/welcome#index'

    #delete '/admins/sign_out', to: 'site/welcome#index'
    #get 'index', to:'site/welcome#index'
  root to: 'site/welcome#index'

end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  paginates_per 5

end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/admin_statistic.rb
class AdminStatistic < ApplicationRecord
end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  paginates_per 5
end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/question.rb
class Question < ApplicationRecord
  # suject conhece question e question conhece subject
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers
  # reject_if rejeita dados em branco de answers que vierem da view
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  paginates_per 5



  # metodos estáticos
  # #pode retirar o nome Question
  # #métodos de classe
  def self.search(page, term)
    Question.includes(:answers)
            .where("lower(description) LIKE ?", "%#{term.downcase}%")
            .page(page)
  end
  def self.last_questions(page)
    Question.includes(:answers).order('created_at desc').page(page)
  end

  #scopes para pesquisa no BD
  scope :search, ->(page, term){
    includes(:answers, :subject)
    .where("lower(description) LIKE ?", "%#{term.downcase}%")
    .page(page)
  }
  scope :search_subject_, ->(page, subject_id){
    includes(:answers,:subject)
      .where(subject_id: subject_id)
      .page(page)
  }

  scope :last_questions, ->(page){
   includes(:answers,:subject)
     .order('created_at desc').page(page)
  }


end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/subject.rb
class Subject < ApplicationRecord
  paginates_per 10
  has_many  :questions
end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user_profile
  # permite que os dados de outras tabelas sejam recebidos. E tbm não permite que uma vez
  # criado o perfil, ele não seja excluído
  accepts_nested_attributes_for :user_profile, reject_if: :all_blank
  #validations
  # validação apenas na atualização
  validates :first_name, presence: true, length: {minimum: 3}, on: :update

  private

  #atributos virtuais
  def full_name
    [self.first_name, self.last_name].join(' ')
  end

end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/user_statistic.rb
class UserStatistic < ApplicationRecord
  belongs_to :user

  #virtual attributes
  def total_questions
    self.right_questions + wrong_questions
  end

  def self.set_statistic(answer, current_user)
    if !!current_user
      user_statistic = UserStatistic.find_or_create_by(user: current_user)
      answer.correct? ? user_statistic.right_questions += 1 : user_statistic.wrong_questions += 1
      user_statistic.save
    end
  end

end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Set Layout
  layout :layout_by_resource
  before_action :check_pagination :set_global_params

  protected
  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
  end

  def check_pagination
    unless user_signed_in?
      params.extract!(:page)
    end
  end

  def set_global_params
    $global_params = params
  end
end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/site_controller.rb
class SiteController < ApplicationController
end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/application_helper.rb
module ApplicationHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/site_helper.rb
module SiteHelper
  def msg_topo
    case params[:action]
    when 'index'
      "Últimas perguntas cadastradas"
    when 'questions'
      "Resultados para o termo: #{params[:term]}"
    when 'subject'
      "Exibindo as questões para o assunto: #{params[:subject_name]}"
    end
  end

end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/views/layouts/admin_devise.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>TimeToAnswer</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

   <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'admin_devise' %>

</head>

<body class="bg-gradient-primary">

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                </div>
                <div class="user">
                  <%= yield %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>


<%= javascript_pack_tag 'application' %>


</body>

</html>

04 - Projeto_Time_to_Answer/time_to_answer/app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>


  <title>TimeToAnswer</title>

  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

   <%= stylesheet_link_tag 'application' %>
   <%= stylesheet_link_tag 'admins_backoffice' %>

</head>

<body id="page-top">


<!-- Page Wrapper -->
<div id="wrapper">

  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <!--
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
       -->
      <div class="sidebar-brand-text mx-3">Backoffice Admin</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

      <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Serviços
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">

    <!-- Nav Item - Charts -->
    <li class="nav-item">
      <div class="nav-link">
        <%= link_to admins_backoffice_admins_index_path do %>
          <i class="fa fa-users fa-fw"></i>
          <span style="color: #FFFFFF">Administradores</span>
        <% end %>
      </div>
    </li>
    <li class="nav-item">
        <%= link_to admins_backoffice_subjects_path, method: :get, class:"nav-link" do %>
          <i class="fa fa-file fa-fw" ></i>
        <span style="color: #FFFFFF">Assuntos/Áreas</span>
        <% end %>
      </li>
    <li class="nav-item">
      <%= link_to admins_backoffice_questions_index_path, method: :get, class:"nav-link" do %>
        <i class="fa fa-th-list fa-fw" ></i>
        <span style="color: #FFFFFF">Perguntas</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to destroy_admin_session_path, method: :get, class:"nav-link" do %>
        <i class="fas fa-share"></i>
        <span style="color: #FFFFFF">Logout</span>
      <% end %>
    </li>


    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <!--
      <div class="text-center d-none d-md-inline">
       <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    -->
    <!-- Sidebar Message
    <div class="sidebar-card d-none d-lg-flex">
      <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="...">
      <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
      <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
    </div>
    -->
  </ul>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
          <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search
        <form
          class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                   aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>-->

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

          <!-- Nav Item - Search Dropdown (Visible Only XS) -->
          <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
              <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                  <input type="text" class="form-control bg-light border-0 small"
                         placeholder="Search for..." aria-label="Search"
                         aria-describedby="basic-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li>


          <div class="topbar-divider d-none d-sm-block"></div>



        </ul>

      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid">

       <!-- Content Row -->

        <div class="row">

          <!-- Area Chart -->
          <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Admimistradores</h6>
                <div class="dropdown no-arrow">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                     data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                       aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Dropdown Header:</div>
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </div>
              </div>

              <div class="card-body">
                 <div class="chart-area">
                  <% if notice %>
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                      <%= notice %>
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                  <% end %>
                  <%= yield %>
                 </div>
              </div>
           </div>
         </div>
        </div>
      </div>
    </div>
  </div>
</div>
  <!-- End of Content Wrapper -->

</div>


<%= javascript_pack_tag 'application' %>
<%= javascript_pack_tag 'admins_backoffice' %>


</body>

</html>

04 - Projeto_Time_to_Answer/time_to_answer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>TimeToAnswer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'site' %>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<div class="container">

  <!-- Static navbar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#"></a> -->
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li class="dropdown-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
          <li><a href="../navbar-static-top/">Static top</a></li>
          <li><a href="../navbar-fixed-top/">Fixed top</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <%= form_with url: site_search_path, local: true, class:'form-inline my-2 my-lg-0', method: :get do |form| %>
    <%= form.text_field :term, class:"form-control", placeholder:"Digite aqui..." %>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
  <% end %>
  <br>
  <br>
  <%= yield %>
  <br>

</div>
<%= javascript_pack_tag 'application' %>

</body>
</html>

04 - Projeto_Time_to_Answer/time_to_answer/app/views/layouts/user_devise.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>TimeToAnswer</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'user_devise' %>

</head>

<body class="bg-gradient-primary">

<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">

    <div>

      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">

              <div class="p-5">
                <div class="text-center">
                </div>
                <div class="user">
                   <%= yield %>
                </div>
              </div>

          </div>
        </div>
      </div>

    </div>

  </div>

</div>


<%= javascript_pack_tag 'application' %>


</body>

</html>

04 - Projeto_Time_to_Answer/time_to_answer/app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>


  <title>TimeToAnswer</title>

  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'users_backoffice' %>

</head>

<body id="page-top">


<!-- Page Wrapper -->
<div id="wrapper">

  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <!--
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
       -->
      <div class="sidebar-brand-text mx-3">Backoffice User, <%= current_user.full_name %></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Serviços
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">


      <!-- Nav Item - Charts -->

    <li class="nav-item">
      <%= link_to users_backoffice_welcome_index_path, method: :get, class:"nav-link" do %>
        <i class="fas fa-share"></i>
        <span style="color: #FFFFFF">Início</span>
      <% end %>
    </li>


    <li class="nav-item">
      <%= link_to users_backoffice_profile_path, method: :get, class:"nav-link" do %>
        <i class="fas fa-share"></i>
        <span style="color: #FFFFFF">Dados do Perfil</span>
      <% end %>
    </li>


    <li class="nav-item">
      <%= link_to destroy_user_session_path, method: :get, class:"nav-link" do %>
        <i class="fas fa-share"></i>
        <span style="color: #FFFFFF">Logout</span>
      <% end %>
    </li>




    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <!--
      <div class="text-center d-none d-md-inline">
       <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    -->
    <!-- Sidebar Message
    <div class="sidebar-card d-none d-lg-flex">
      <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="...">
      <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
      <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
    </div>
    -->
  </ul>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
          <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search
        <form
          class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                   aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>-->

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

          <!-- Nav Item - Search Dropdown (Visible Only XS) -->
          <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
              <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                  <input type="text" class="form-control bg-light border-0 small"
                         placeholder="Search for..." aria-label="Search"
                         aria-describedby="basic-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li>


          <div class="topbar-divider d-none d-sm-block"></div>



        </ul>

      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid">

        <!-- Content Row -->

        <div class="row">

          <!-- Area Chart -->
          <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div
                class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Usuários</h6>
                <div class="dropdown no-arrow">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                     data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                       aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Dropdown Header:</div>
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </div>
              </div>

              <div class="card-body">
                <div class="chart-area">
                  <% if notice %>
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                      <%= notice %>
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                  <% end %>
                  <%= yield %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End of Content Wrapper -->

</div>


<%= javascript_pack_tag 'application' %>
<%= javascript_pack_tag 'users_backoffice' %>


</body>

</html>