04 - Projeto_Time_to_Answer/time_to_answer/config/routes.rb
Rails.application.routes.draw do

  namespace :admins_backoffice do
    get 'admins/index' #dasboard
    #get 'admins/edit/:id', to: "admins#edit"
    resource :admins #Adminsitradores
    resource :subjects # Assuntos
    resource :questions
    get 'questions/index' #index questions
  end
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    post 'answer', to: 'answer#question'
    get 'subject/:subject_id/:subject_name', to: 'search#subject', as: 'search_subject'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to:'profile#edit'
    #atualização do registro (patch - parte dos dados ou put - todos os dados)
    patch 'profile', to:'profile#update'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  # Bloqueia a rota /admins/sign_up
  #devise_for :admins, :skip => [:registrations] do
  devise_for :admins do
     get 'admins/sign_out', to: 'devise/sessions#destroy'
  end

  devise_for :users

  get 'backoffice', to: 'admins_backoffice/welcome#index'

    #delete '/admins/sign_out', to: 'site/welcome#index'
    #get 'index', to:'site/welcome#index'
  root to: 'site/welcome#index'

end

04 - Projeto_Time_to_Answer/time_to_answer/app/models/question.rb
class Question < ApplicationRecord
  # suject conhece question e question conhece subject
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers
  # reject_if rejeita dados em branco de answers que vierem da view
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  paginates_per 5



  # metodos estáticos
  # #pode retirar o nome Question
  # #métodos de classe
  def self.search(page, term)
    Question.includes(:answers)
            .where("lower(description) LIKE ?", "%#{term.downcase}%")
            .page(page)
  end
  def self.last_questions(page)
    Question.includes(:answers).order('created_at desc').page(page)
  end

  #scopes para pesquisa no BD
  scope :search, ->(page, term){
    includes(:answers, :subject)
    .where("lower(description) LIKE ?", "%#{term.downcase}%")
    .page(page)
  }
  scope :search_subject_, ->(page, subject_id){
    includes(:answers,:subject)
      .where(subject_id: subject_id)
      .page(page)
  }

  scope :last_questions, ->(page){
   includes(:answers,:subject)
     .order('created_at desc').page(page)
  }


end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verifyPasswordAndPassword_confirmationIsNotNull, :search_admin_update, only: [:update]
  before_action :search_admin, only: [:edit, :destroy]

  def index
     @admins = Admin.all.page(params[:page])
  end

  # Ao clicar no botão de edição de um elemente
  def edit
  end

  # Ao clicar no botão atualizar
  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_index_path, notice: "Administrador atualizado."
    else
      render :edit
    end
  end

  # Ao clicar no botão adicionar novo elemento
  def new
    @admin = Admin.new
  end

  # Ao salvar um novo elemento de fato
  def create
    @admin = Admin.new(params_admin)
    if @admin.save()
      redirect_to admins_backoffice_admins_index_path, notice: "Administrador cadastrado."
    else
      render :new
    end
  end
  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_index_path, notice: "Administrador excluído."
    else
      render :index
    end
  end

  # Possibilitando que esses métodos fiquem encapsulados
  private

  def params_admin
    params.require(:admin).permit(:id,:email,:password,:password_confirmation)
  end
  def search_admin
    @admin = Admin.find(params[:format])
  end
  def search_admin_update
    @admin = Admin.find(params[:admin][:id])
  end
  def verifyPasswordAndPassword_confirmationIsNotNull
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
       params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :search_question, only: [:edit, :destroy]
  before_action :search_question_update, only: [:update]
  before_action :search_subjects, only: [:edit, :new]

  def index
    @questions = Question.all.includes(:subject)
                         .order(:description)
                         .page(params[:page])

  end

  # Ao clicar no botão de edição de um elemento
  def edit
  end

  # Ao clicar no botão atualizar
  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_index_path, notice: "Questão atualizada."
    else
      render :index
    end
  end

  # Ao clicar no botão adicionar novo elemento
  def new
    @question = Question.new
    3.times { @question.answers.build}
  end

  # Ao salvar um novo elemento de fato
  def create
    @question = Question.new(params_question)
    if @question.save()
      redirect_to admins_backoffice_questions_index_path, notice: "Questão cadastrada."
    else
      render :index
    end
  end
  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_index_path, notice: "Questão excluída."
    else
      render :index
    end
  end

  # Possibilitando que esses métodos fiquem encapsulados
  private

  def params_question
    params.require(:question).permit(:id,:description,:subject_id,
                                     answers_attributes: [:id, :description, :correct, :_destroy])
  end
  def search_question
    @question = Question.find(params[:format])
  end
  def search_subjects
    @subjects = Subject.all
  end
  def search_question_update
    @question = Question.find(params[:question][:id])
  end
end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :search_subject, only: [:edit, :destroy]
  before_action :search_subject_update, only: [:update]

  def show
    @subjects = Subject.all.order(:description).page(params[:page])
  end

  # Ao clicar no botão de edição de um elemente
  def edit
  end

  # Ao clicar no botão atualizar
  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto atualizado."
    else
      render :edit
    end
  end

  # Ao clicar no botão adicionar novo elemento
  def new
    @subject = Subject.new
  end

  # Ao salvar um novo elemento de fato
  def create
    @subject = Subject.new(params_subject)
    if @subject.save()
      redirect_to admins_backoffice_subjects_path, notice: "Assunto cadastrado."
    else
      render :new
    end
  end
  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto excluído."
    else
      render :index
    end
  end

  # Possibilitando que esses métodos fiquem encapsulados
  private

  def params_subject
    params.require(:subject).permit(:id,:description)
  end
  def search_subject
    @subject = Subject.find(params[:format])
  end
  def search_subject_update
    @subject = Subject.find(params[:subject][:id])
  end
 end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @total_users = AdminStatistic.find_by_event(AdminStatistic::EVENTS[:total_users])
    @total_questions = AdminStatistic.find_by_event(AdminStatistic::EVENTS[:total_questions])
  end
end

04 - Projeto_Time_to_Answer/time_to_answer/app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

04 - Projeto_Time_to_Answer/time_to_answer/app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested_fields">
  <%= f.label :description %></br>
  <%= f.text_field :description %>

  <%= f.check_box :correct %> Correta?

  <div class="links">
    <%= link_to_remove_association('remover',f) %>
  </div>
</div>

04 - Projeto_Time_to_Answer/time_to_answer/app/views/admins_backoffice/questions/edit.html.erb
<%= render partial:'admins_backoffice/questions/shared/form',
           locals: {action_message: 'Editar'}
%>

04 - Projeto_Time_to_Answer/time_to_answer/app/views/admins_backoffice/questions/index.html.erb
<h2>Olá, Estou na Questions-Controller</h2>

<h3><%= t('messages.listing', model: @questions.model_name.human(count:2))%></h3>

<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col"><%= @questions.model.human_attribute_name(:id) %></th>
    <th scope="col"><%= @questions.model.human_attribute_name(:description) %></th>
    <th scope="col"><%= @questions.model.human_attribute_name(:subject) %></th>
    <th>
      <%= link_to new_admins_backoffice_questions_path, class:"btn btn-success btn-circle" do%>
        <i class="fa fa-plus" style="color: #FFFFFF;"></i>
      <% end %>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @questions.each do |question| %>
    <tr>
      <th scope="row"><%= question.id %></th>
      <td><%= question.description.truncate(50) %></td>
      <td><%= question.subject.description.truncate(30) %></td>
      <td style="width: 150px;">
        <%= link_to edit_admins_backoffice_questions_path(question), class:"btn btn-primary btn-circle"  do %>
          <i class="fa fa-edit" style="color: #FFFFFF;"></i>
        <% end %>
        <%= button_to admins_backoffice_questions_path(question), method: :delete, class:"btn btn-danger btn-circle", data: { confirm: t('messages.confirm_with', item:question.description.truncate(15)) } do %>
          <i class="fa fa-minus" style="color: #FFFFFF;"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate @questions %>
</div>

04 - Projeto_Time_to_Answer/time_to_answer/app/views/admins_backoffice/questions/new.html.erb
<%= render partial:'admins_backoffice/questions/shared/form',
           locals: {action_message: 'Nova'}
%>